services:
  goapi:
    container_name: goapi
    image: github.com/pytsx/goapi
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - godb
  godb:
    container_name: godb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}